/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.DaoVerdoce;

/**
 *
 * @author João Paulo
 */
public class ViewIndex extends javax.swing.JFrame {

    /**
     * Creates new form ViewIndex
     */
    public ViewIndex() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnVender = new javax.swing.JButton();
        btnCompraVenda = new javax.swing.JButton();
        btnVender1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuGere = new javax.swing.JMenu();
        paletaAddProduto = new javax.swing.JMenuItem();
        paletaRemoveProduto = new javax.swing.JMenuItem();
        paletaEditarProduto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Charlemagne Std", 1, 36)); // NOI18N
        jLabel1.setText("Verdoce");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel1)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        btnVender.setFont(new java.awt.Font("Charlemagne Std", 0, 14)); // NOI18N
        btnVender.setText("Vender produto");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        btnCompraVenda.setFont(new java.awt.Font("Charlemagne Std", 0, 14)); // NOI18N
        btnCompraVenda.setText("Compras/Vendas");
        btnCompraVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraVendaActionPerformed(evt);
            }
        });

        btnVender1.setFont(new java.awt.Font("Charlemagne Std", 0, 14)); // NOI18N
        btnVender1.setText("Cadastrar cliente");
        btnVender1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVender1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVender1)
                    .addComponent(btnCompraVenda)
                    .addComponent(btnVender))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(btnVender1)
                .addGap(18, 18, 18)
                .addComponent(btnVender)
                .addGap(30, 30, 30)
                .addComponent(btnCompraVenda)
                .addGap(76, 76, 76))
        );

        menuGere.setText("Gerenciamento");

        paletaAddProduto.setText("Adicionar produto");
        paletaAddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paletaAddProdutoActionPerformed(evt);
            }
        });
        menuGere.add(paletaAddProduto);

        paletaRemoveProduto.setText("Remover produto");
        paletaRemoveProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paletaRemoveProdutoActionPerformed(evt);
            }
        });
        menuGere.add(paletaRemoveProduto);

        paletaEditarProduto.setText("Editar produto");
        menuGere.add(paletaEditarProduto);

        jMenuBar1.add(menuGere);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //DaoVerdoce.gravar();
    }//GEN-LAST:event_formWindowOpened

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        ViewVender vv = new ViewVender();
        vv.setVisible(true);
        vv.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnVenderActionPerformed

    private void btnCompraVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraVendaActionPerformed
        // TODO add your handling code here:
        ViewMostrarDados vm = new ViewMostrarDados();
        vm.setVisible(true);
        vm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnCompraVendaActionPerformed

    private void paletaRemoveProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paletaRemoveProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paletaRemoveProdutoActionPerformed

    private void paletaAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paletaAddProdutoActionPerformed
        // TODO add your handling code here:
        ViewAddProduto vp = new ViewAddProduto();
        vp.setVisible(true);
        vp.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_paletaAddProdutoActionPerformed

    private void btnVender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVender1ActionPerformed
        // TODO add your handling code here:
        ViewAddCliente vc = new ViewAddCliente();
        vc.setVisible(true);
        vc.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_btnVender1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewIndex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompraVenda;
    private javax.swing.JButton btnVender;
    private javax.swing.JButton btnVender1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu menuGere;
    private javax.swing.JMenuItem paletaAddProduto;
    private javax.swing.JMenuItem paletaEditarProduto;
    private javax.swing.JMenuItem paletaRemoveProduto;
    // End of variables declaration//GEN-END:variables
}
